#! /bin/bash

### Settings
# Paths in Docker container
OCTAVE_PATH=/opt/remtg
TMP=/var/tmp
RTDIR=/srv/data
DEF=${RTDIR}/rtg_def.m
# Default value
NDUMPS=60

### Main

# Path for octave fcn 'tempname'
export TMP
# Path for octave fcn 'tempdir'
export TMPDIR=$TMP

# disable FLTK graphics (important)
unset DISPLAY

# Run wtg
export WTG="rtdir='$RTDIR';,webtg=$NDUMPS;,def_file='$DEF';,selax.wtg='';,upload=0;"
octave-cli -q -p $OCTAVE_PATH --eval wtg
