#!/bin/bash -l
if [ -z "$matlab" ]; then
 matlab=matlab
fi
prog=`which $matlab`
if [ $? -ne 0 ]; then
 prog=octave
fi
#find remtg directory
filename=$0
while [ -h $filename ]; do
	lscmd=`ls -l $filename 2>/dev/null`
	f1=`echo "$lscmd" | gawk '{ print $NF }'`
	fp=`echo "$f1" | gawk '{ print index($1,"/") }'`
	if [ $fp != "1" ];then
		filename=`dirname $filename`/$f1
	else
		filename=$f1
	fi
done
MATLABPATH=`dirname $filename`
#echo $MATLABPATH
umask 002
TMP=$HOME/tmp
if [ ! -d $TMP ];then
 mkdir $TMP
fi
SHELL=/bin/sh
for utf in `env | grep UTF`
do
 unset `echo $utf | awk -F = '{ print $1 }'`
done
usage="Usage: rtg [-v] [-s KSTVL2PZ]"
term=0
jvm="-nodesktop"
while getopts ojts: flag
do
 case $flag in
  t) term=1;;
  j) jvm="-nojvm";;
  o) prog=octave;;
  s) EISCATSITE="$OPTARG"
     export EISCATSITE;;
  ?) echo $usage
     exit 2;;
 esac
done
shift `expr $OPTIND - 1`
if [[ $prog =~ .*octave ]];then
 OCTAVE_PATH=$MATLABPATH
 TMPDIR=$TMP
 export OCTAVE_PATH TMPDIR
 comm="$prog --no-gui --persist --eval rtg"
else 
 comm="$prog $jvm -nosplash -r rtg"
fi
if [ $term -eq 0 ]
then
 XTERM_WM_NAME=`xprop -id $WINDOWID WM_NAME 2>/dev/null | sed 's/WM_NAME(STRING) =[ "]*\([^"]*\)["]/\1/'`
 export MATLABPATH SHELL XTERM_WM_NAME TMP
 exec $comm
else
 XTERM_WM_NAME=rtg$EISCATSITE
 export MATLABPATH SHELL XTERM_WM_NAME TMP
 xterm -title rtg$EISCATSITE -bg white -fg blue -geometry 60x5-20+800 \
  -sb -sl 256 -fn fixed -e $comm &
fi
