#!/bin/sh
#find remtg directory
filename=$0
while [ -h $filename ]; do
	lscmd=`ls -l $filename 2>/dev/null`
	f1=`echo "$lscmd" | awk '{ print $NF }'`
	fp=`echo "$f1" | awk '{ print index($1,"/") }'`
	if [ $fp != "1" ];then
		filename=`dirname $filename`/$f1
	else
		filename=$f1
	fi
done
MATLABPATH=`dirname $filename`
#echo $MATLABPATH
umask 002
TMP=$HOME/tmp
if [ ! -d $TMP ];then
 mkdir $TMP
fi
SHELL=/bin/sh
XTERM_WM_NAME=`xprop -id $WINDOWID WM_NAME 2>/dev/null | sed 's/WM_NAME(STRING) =[ "]*\([^"]*\)["]/\1/'`
unset `env | grep UTF | awk -F = '{ print $1 }'`
usage="Usage: rtg [-v] [-s KSTVL2PZ]"
term=0
while getopts ts: flag
do
 case $flag in
  t) term=1;;
  s) EISCATSITE="$OPTARG"
     export EISCATSITE;;
  ?) echo $usage
     exit 2;;
 esac
done
shift `expr $OPTIND - 1`
export MATLABPATH SHELL XTERM_WM_NAME TMP
comm="matlab -nojvm -nosplash -r rtg"
if [ $term -eq 0 ]
then
 exec $comm
else
 xterm -title rtg$EISCATSITE -bg white -fg blue -geometry 60x5-20+800 \
  -sb -sl 256 -fn fixed -e $comm &
fi
