#!/bin/bash -l
if [ -z "$matlab" ]; then
 matlab=matlab
fi
prog=`which $matlab`
if [ $? -ne 0 ]; then
 prog=octave
fi
MSTART=rtg
#find remtg directory
filename=`realpath $0`
MATLABPATH=`dirname $filename`
#echo $MATLABPATH
umask 002
TMP=$HOME/tmp
SHELL=/bin/sh
for utf in `env | grep UTF`
do
 unset `echo $utf | awk -F = '{ print $1 }'`
done
usage="Usage: rtg [-o] [-s KSTVL2PZ] [-x]"
term=0
while getopts otxs: flag
do
 case $flag in
  t) term=1;;
  o) prog=octave;;
  x) MSTART=;;
  s) EISCATSITE="$OPTARG"
     export EISCATSITE;;
  ?) echo $usage
     exit 2;;
 esac
done
shift `expr $OPTIND - 1`
if [[ $prog =~ .*octave ]];then
 OCTAVE_PATH=$MATLABPATH
 TMPDIR=$TMP
 export OCTAVE_PATH TMPDIR SHELL
 if [ $MSTART ]; then MSTART="--eval $MSTART"; fi
 comm="$prog --no-gui --persist $MSTART"
else 
 export MATLABPATH TMP SHELL
 if [ $MSTART ]; then MSTART="-r $MSTART"; fi
 comm="$prog -nodesktop -nosplash $MSTART $*"
fi
if [ $term -eq 0 ]
then
 XTERM_WM_NAME=`xprop -id $WINDOWID WM_NAME 2>/dev/null | sed 's/WM_NAME(STRING) =[ "]*\([^"]*\)["]/\1/'`
 export XTERM_WM_NAME
 exec $comm
else
 XTERM_WM_NAME=rtg$EISCATSITE
 export XTERM_WM_NAME
 xterm -title rtg$EISCATSITE -bg white -fg blue -geometry 60x5-20+800 \
  -sb -sl 256 -fn fixed -e $comm &
fi
