#!/bin/bash
rtdir=
def=
slx=
null=">/dev/null"
if [ -z "$matlab" ]; then
 matlab=matlab
fi
prog=`which $matlab`
if [ $? -ne 0 ]; then
 matlab=`which octave-cli`
 if [ $? -ne 0 ]; then
  matlab=octave
 fi
fi
#find remtg directory
filename=`realpath $0`
MATLABPATH=`dirname $filename`
TMP=$HOME/tmp
ndumps="60"
usage="Usage: webtg [-o] [-O] [-v] [-t] [-d dir] [-s KSTVL2PZ] [-D def] [-x fig,subplot,routine] [-n dumps/secs] [start] | stop"
while getopts oOvtd:D:s:n:x: flag
do
 case $flag in
  v) null=;;
  d) rtdir="$OPTARG";;
  D) def="$OPTARG";;
  x) slx="$OPTARG";;
  s) EISCATSITE="$OPTARG"
     export EISCATSITE;;
  n) ndumps="$OPTARG";;
  o) matlab="octave-cli";;
  O) matlab="octave";;
  t) TMP="$PWD";;
  ?) echo $usage
     exit 2;;
 esac
done
shift `expr $OPTIND - 1`
if [ ! -d $TMP ];then
 mkdir $TMP
fi
if [ `echo $matlab | grep octave` ];then
 TMPDIR=$TMP
 OCTAVE_PATH=$MATLABPATH
 export OCTAVE_PATH TMPDIR
fi
if [ "$*" = "stop" ];then
 /bin/ps -u kstdev -u eiscat | awk '/webtg/ && ! /awk/ {print "ps  -fu kstdev -u eiscat | grep " $1 " | grep $matlab"}' | /bin/sh | awk '{print $2}' | xargs kill -9 >/dev/null
elif [ "$*" = "start" ] || [ "$*" = "" ];then
 SHELL=/bin/sh
 WTG="rtg_startup,wtg('$rtdir',$ndumps,'$def','$slx'),exit"
 export MATLABPATH SHELL TMP
 unset DISPLAY
 if [ -z "$OCTAVE_PATH" ];then
  $matlab -nodisplay <<< "$WT" $null
 elif [ $matlab = "octave" ]; then
  $matlab -q -p $OCTAVE_PATH <<< "$WT"
 else
  $matlab -Wq <<< "$WT"
 fi
else
 echo $usage
 exit 1
fi
