#!/bin/sh
rtdir=
null=">/dev/null"
ndumps="60"
usage="Usage: webtg [-v] [-d dir] [-s KSTVL2PZ] [-n dumps/secs] [start] | stop"
while getopts vd:s:n: flag
do
 case $flag in
  v) null=;;
  d) rtdir="$OPTARG";;
  s) EISCATSITE="$OPTARG"
     export EISCATSITE;;
  n) ndumps="$OPTARG";;
  ?) echo $usage
     exit 2;;
 esac
done
shift `expr $OPTIND - 1`
#find remtg directory
filename=$0
while [ -h $filename ]; do
        lscmd=`ls -l $filename 2>/dev/null`
        f1=`echo "$lscmd" | awk '{ print $NF }'`
        fp=`echo "$f1" | awk '{ print index($1,"/") }'`
        if [ $fp != "1" ];then
                filename=`dirname $filename`/$f1
        else
                filename=$f1
        fi
done
MATLABPATH=`dirname $filename`
#echo $MATLABPATH
if [ "$*" = "stop" ];then
 /bin/ps -u kstdev -u eiscat | awk '/webtg/ && ! /awk/ {print "ps  -fu kstdev -u eiscat | grep " $1 " | grep matlab"}' | /bin/sh | awk '{print $2}' | xargs kill -9 >/dev/null
elif [ "$*" = "start" ] || [ "$*" = "" ];then
 SHELL=/bin/sh

 TMP=$HOME/tmp
 if [ ! -d $TMP ];then
  mkdir $TMP
 fi
 export MATLABPATH SHELL TMP
 unset DISPLAY
 matlab $null << !
  global rtdir webtg
  rtdir='$rtdir'
  webtg=$ndumps
  rtg_startup
  while ~remtg, end
 exit
!
else
 echo $usage
 exit 1
fi
